cask_args appdir: "/Applications"

brew "act"
brew "cloc"
brew "ffmpeg"
brew "fswatch"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "graphviz"
brew "jq"
brew "lefthook"
brew "lsyncd"
brew "mint"
brew "mise"
brew "nodebrew"
brew "openapi-generator"
brew "pandoc"
brew "pinentry-mac"
brew "pipx"
brew "rbenv"
brew "rsync"
brew "swiftlint"
brew "tesseract"
brew "tokei"
brew "tree"
brew "yarn"
brew "zsh-autosuggestions"
brew "zsh-completions"

cask "font-firgenerd"
cask "font-hackgen"
cask "jordanbaird-ice"
cask "keycastr"
cask "multipass"
cask "reminders-menubar"
cask "xcodes-app"
