version: 2.1

orbs:
  shellcheck: circleci/shellcheck@3.1.2

jobs:
  shellcheck:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - shellcheck/check

workflows:
  shellcheck-workflow:
    jobs:
      - shellcheck
