alias ls='ls --color=auto'
alias ghqcd='`ghq list --full-path | peco`'
alias gs='git status'
alias gsw='git switch `git branch | peco`'
alias gswpr='peco-checkout-pull-request'
alias gswd='switch-default-branch-if-exists'
alias gbr='git branch --show-current'
alias gus='git reset HEAD --'
alias tree='cmd="command tree -a -I .git"; echo $cmd; eval ${cmd}'
alias rmb='git branch --merged | xargs -n 1 | egrep -v "main|develop|\*" | xargs git branch -d'
alias rm='trash-put'
